### ISSUE TITLE
wrong libexecdir on ubuntu

### ISSUE THREAD

**Issue by stsp** [dosemu2/install-freedos#10]
dosemu2 gets the libexecdir via dh_auto_configure.
But install-freedos only uses dh_auto_install and
doesn't get the libexecdir.
I tried the $(libexecdir) and $(prefix) variables,
but they do not exist in dh_auto_install.

@skitt could you please tell me how to access
the ubuntu directories in dh_auto_install
(eg for the packages w/o configure)?

**Comment by skitt** [comment]
There’s no automatic way to calculate `libexecdir` (except with Autoconf or Meson); in this instance, you should override it in `debian/rules`:

    dh_auto_install $@ -- prefix=/usr libexecdir=/usr/lib/$(DEB_HOST_MULTIARCH)

(with an `include /usr/share/dpkg/default.mk` earlier in `debian/rules`).

**Comment by stsp** [comment]
Yes, I was exactly asking about an
override. Are there more convenient
macros like $(prefix) $(libexec) etc?
Eg in the example above, you hard-code
prefix and half-hardcode libexec so
how would you guarantee they are
going to match what was in dh_auto_configure?

**Comment by skitt** [comment]
`dh_auto_configure` doesn’t matter; what matters is Debian Policy, at the version referred to in `debian/control` (3.9.7 in `install-freedos`). In that version, `libexec` isn’t recognised, and files that would typically be installed there in distributions with `libexec`, should go under `/usr/lib/$(DEB_HOST_MULTIARCH)`. (The hard-coded `prefix` is already present in the current `debian/rules`, I didn’t add it.)

`dh_auto_configure`, and all the other Debhelper tools, are helpers — their role is to reduce the amount of boilerplate in Debian packages, not to provide an authoritative source of truth.

Note that as far as `libexec` goes, Policy 4.1.5 switched to version 3.0 of the FHS, which allows its use; and in compatibility level 12 or higher, `dh_auto_configure` no longer sets it, since the default `${prefix}/libexec` is acceptable in relevant versions of Policy.

**Comment by stsp** [comment]
dh_auto_configure matters here because
it does this to dosemu2:
```
cd build && ../configure --build=x86_64-linux-gnu --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man
 --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules
 --libdir=\${prefix}/lib/x86_64-linux-gnu --libexecdir=\${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode
 --disable-dependency-tracking
```

The question is only where does
it get all these flags, and can I access
them manually, as I can do in rpm:
`%{libexecdir}`.

But I guess there is no such possibility,
or otherwise you would already have
told me about it. :) So I'll do what you
said above. Prefix is hard-coded simply
because I didn't know where to get it
properly. Where does dh_auto_configure
get these all?

**Comment by skitt** [comment]
> dh_auto_configure matters here because
> it does this to dosemu2:

Really, no, it doesn’t matter, but I don’t care enough to argue the point so feel free to ignore me. Like I said above, `dh_auto_configure` no longer specifies `--libexecdir` in current compatibility levels.

> But I guess there is no such possibility,
> or otherwise you would already have
> told me about it. :) So I'll do what you
> said above. Prefix is hard-coded simply
> because I didn't know where to get it
> properly. Where does dh_auto_configure
> get these all?

They’re hard-coded in the build-system support modules in Debhelper. Look at `/usr/share/perl5/Debian/Debhelper/Buildsystem/autoconf.pm` for example.

**Comment by stsp** [comment]
OK, I see what you mean: that I need
to set compat to 12 in dosemu2 and touch
nothing in install-freedos, and then
dh_auto_configure won't matter when
talking about libexec (but my question
was about all such paths, eg I don't like
the hard-coded prefix too - I'd better get
it from where dh_auto_configure gets it).

So this is what I'll do right now and we'll
see how it goes, thanks for info!

**Comment by skitt** [comment]
> OK, I see what you mean: that I need
> to set compat to 12 in dosemu2 and touch
> nothing in install-freedos, and then
> dh_auto_configure won't matter when
> talking about libexec (but my question
> was about all such paths, eg I don't like
> the hard-coded prefix too - I'd better get
> it from where dh_auto_configure gets it).

Debian isn’t Fedora (and yes, some aspects of RPM macros are nice, I’m not saying one is better than the other). It’s fine to have hard-coded paths in `debian/rules` etc., because the reference isn’t any build tool, it’s Policy. So we declare we comply with a certain version of Policy, using the `Standards-Version` field in `debian/control`; and that (Policy) is the source of truth.

Again, `debhelper` is only a helper, not a source of truth.

**Comment by stsp** [comment]
OK but debhelper could provide the
macros to access the properties of
the aforementioned policy.
But it doesn't. :(
The upside would be that you change
the policy version and everything else
adjusts.
But if you hard-code everything, then
you change standard and get inconsistent
configuration unless you update everything
by hands. Debhelper should really automate
the things like that.

**Comment by stsp** [comment]
This seems fixed.
